### ISSUE TITLE
Cannot Create Schedule Interval (Firefox)

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-ui-go#183]
I am attempting to create a schedule interval using the nightly build docker-compose [file](https://github.com/edgexfoundry/developer-scripts/blob/master/releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml). I am using the Firefox browser (v.73.0.1).

When attempting to create a schedule interval, I am unable to save my work by clicking on the check-mark icon shown in the attached screenshot. I click the check-mark but nothing happens.
<img width="1127" alt="Screen Shot 2020-04-07 at 10 18 09 AM" src="https://user-images.githubusercontent.com/1342980/78686853-2566d300-78b9-11ea-8bdb-76450e7cd259.png">

The dialog will close if I click the "X" but then none of my work is saved.

**Comment by DaveZLB** [comment]
@tsconn23 , due to network, I pull  the latest nightly build very slowly，I test it as your bug report using the nightly build version three days ago , it‘s ok. at the same time, i noticed your attached screenshot,  there is not  default interval and interval action for edgex,  i guess  you may have a wrong address configuration in the gateway page.  you need to use hostIp instead of localhost.
Gateway pages can be confusing due to design issues, it may removed later.

if you configurate gateway page correctly, it will showed as follows.
![Uploading WeChatbdfe8c28546efaa02152df636c41d39b.png…]()

**Comment by badboy-huaqiao** [comment]
@tsconn23 Does ZLB's reply solve your trouble?

**Comment by tsconn23** [comment]
@DaveZLB If I can't create an interval in the first place, how am I supposed to have a default interval?

With regard to Gateway, I've specified an IP address of 192.168.100.1. I notice you have a Device Service tab. The device virtual container is running for me and sending data, however I see no Device Services reflected in the UI either.

**Comment by DaveZLB** [comment]
@tsconn23 , thanks for your reply , i will continue to follow up this issue.

**Comment by DaveZLB** [comment]
@tsconn23 ， I asked others to test it ,and there is no problem as you described, I am a bit confused now. maybe  you can pull newest ui docker or master ui code for testing. I add some ui  tips. if ui cannot get a heart beat from other edgex services, the small circle will turn red. otherwise, it will be green normally.

![image](https://user-images.githubusercontent.com/29951254/79448826-b6a21c00-8014-11ea-8bcf-2b20ccdb11ee.png)

**Comment by badboy-huaqiao** [comment]
this issue belongs to old version UI, the new UI is done!
<img width="1672" alt="image" src="https://user-images.githubusercontent.com/16172215/121638886-4a0e9a00-cabe-11eb-8b7a-6ab05eea0de3.png">

<img width="1640" alt="image" src="https://user-images.githubusercontent.com/16172215/121638790-23506380-cabe-11eb-9048-6372d57e6e1b.png">
