### ISSUE TITLE
UI not able to create Gateway in Geneva release

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-ui-go#222]
No matter what address is used (localhost, IP of the host or 127.0.0.1), the UI cannot successfully create and connect a gateway to Geneva release EdgeX.  Get the following log entries (regardless if running with or without security on)
edgex-ui-go          | 2020/05/14 16:07:19 Loading configuration from: /go/src/github.com/edgexfoundry/edgex-ui-go/cmd/edgex-ui-server/res/docker/configuration.toml
edgex-ui-go          | 2020/05/14 16:07:19 Connect to memoryDB success !
edgex-ui-go          | 2020/05/14 16:07:19 EdgeX UI Server Listen On :4000
edgex-ui-go          | 2020/05/14 16:52:36 User: admin login
edgex-ui-go          | 2020/05/14 16:54:24 http: proxy error: dial tcp 192.168.0.13:48081: connect: connection refused
edgex-ui-go          | 2020/05/14 16:54:24 http: proxy error: dial tcp 192.168.0.13:48082: connect: connection refused
edgex-ui-go          | 2020/05/14 16:54:24 http: proxy error: dial tcp 192.168.0.13:48081: connect: connection refused
edgex-ui-go          | 2020/05/14 16:54:24 http: proxy error: dial tcp 192.168.0.13:48081: connect: connection refused
edgex-ui-go          | 2020/05/14 16:54:31 http: proxy error: dial tcp 192.168.0.13:48085: connect: connection refused
edgex-ui-go          | 2020/05/14 16:54:31 http: proxy error: dial tcp 192.168.0.13:48085: connect: connection refused
edgex-ui-go          | 2020/05/14 16:54:31 http: proxy error: dial tcp 192.168.0.13:48085: connect: connection refused
edgex-ui-go          | 2020/05/14 16:56:41 http: proxy error: dial tcp 172.17.0.1:48060: connect: connection refused
edgex-ui-go          | 2020/05/14 16:56:41 http: proxy error: dial tcp 172.17.0.1:48060: connect: connection refused
edgex-ui-go          | 2020/05/14 16:56:41 http: proxy error: dial tcp 172.17.0.1:48060: connect: connection refused

**Comment by DaveZLB** [comment]
@jpwhitemn , I noticed some changes about port mapping in the latest edgex docker compose files from nightly-build version,the snapshots is as follows:
<img width="1414" alt="issue-222" src="https://user-images.githubusercontent.com/29951254/82001646-39f37380-968e-11ea-85b2-6f8149d384f4.png">

 eg.in fuji version port mapping is 4000:4000, but in nightly-build version is 127.0.0.1:4000:4000,
it will cause gateway not work.

**Comment by badboy-huaqiao** [comment]
@jpwhitemn  

Hi Jim. 😊

Well, it looks a little weird.

I totally understand why you bind all services (except for kong) to native 172.0.0.1 with security on. under this way, user only can approach to edgexfoundry through the security API microservice kong.

However, without the security API microservice kong, how can users access edgexfoundry remotely? 

In addition, it only makes sense when the UI can be remote access to , so the UI service should not also be bound to the native 127.0.0.1

The gateway term in the UI is essentially an edgexfoundry instance. We designed it with one view to managing multiple edgexfoundry instances with one UI, rather than one edgexfoundry instance with one UI, which is not conducive to the deployment of multiple edgexfoundry instances into a production environment.

But now the gateway term doesn't seem to be working as well as it should be, or not to make much sense at this point.

Therefore, we will remove the gateway concept in the next release.
However, in order to solve the current problem, I propose to modify the docker-compose file as follows：

the UI section in the docker-compose file:

<img width="510" alt="image" src="https://user-images.githubusercontent.com/16172215/82111380-7949bf00-9777-11ea-8333-292ded90e32a.png">

**Comment by badboy-huaqiao** [comment]
@jpwhitemn  under this way , user can only enter the value 172.0.0.1

**Comment by badboy-huaqiao** [comment]
@jpwhitemn By the way, if it still leaves some time and doesn't delay the release of version Geneva, we can immediately remove the gateway concept, which may take one day to modify and debug.

**Comment by DaveZLB** [comment]
done
