### ISSUE TITLE
Gateway addition with 127.0.0.1 address returns "Bad Gateway" in logs

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry/edgex-ui-go#223]
With EdgeX-UI from nightly build docker-compose (Redis/no security), registering in the UI a gateway as 127.0.0.1 (local  edgeX container instance), the health status is red. When I used to run it in a separate VM things worked and registered the gateway it worked. Could this stem from a developer script change: https://github.com/edgexfoundry/developer-scripts/commit/6724119f0a4ce47973625c069eb325f139345ade  ? "bind to 127 with the exception of Kong proxy ports (#268)"

**Comment by DaveZLB** [comment]
I am following this issue,  the details see https://github.com/edgexfoundry/edgex-ui-go/issues/222

发件人: Malini Bhandaru <notifications@github.com>
答复: edgexfoundry/edgex-ui-go <reply@reply.github.com>
日期: 2020年5月15日 星期五 上午7:13
收件人: edgexfoundry/edgex-ui-go <edgex-ui-go@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [edgexfoundry/edgex-ui-go] Gateway addition with 127.0.0.1 address returns "Bad Gateway: in logs (#223)


With EdgeX-UI from nightly build docker-compose (Redis/no security), registering in the UI a gateway as 127.0.0.1 (local edgeX container instance), the health status is red. When I used to run it in a separate VM things worked and registered the gateway it worked. Could this stem from a developer script change: edgexfoundry/developer-scripts@6724119<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fedgexfoundry%2Fdeveloper-scripts%2Fcommit%2F6724119f0a4ce47973625c069eb325f139345ade&data=02%7C01%7Czlibin%40vmware.com%7Cc46b3d4f4a2b412c427508d7f85c5dae%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637250947909626668&sdata=PgGc%2BiL71sqClntUtKiB9JaR4jf4FUa4VaXGilDQVlE%3D&reserved=0> ? "bind to 127 with the exception of Kong proxy ports (#268)"

**Comment by lenny-intel** [comment]
Yes, the lock down of the ports to `127.0.0.1` has broken the UI's ability to access the EdgeX services using a static IP or machine name since docker sees that as a network access. I attempted to use `127.0.0.1`, but that will not route outside the UI container.

This problem stems from the fact that the UI is trying to "connect" and "manage" a gateway rather than just "manage" the EdgeX instance that is is running within. 

My suggestion is to drop the Gateway "connect" and use the docker network host names to connect to the services within the docker network. i.e. edgex-core-data:48080 & edgex-core-metadata:48081

This how all the service communicate with each other within the docker network. I suggest the UI have environment variables for the host names similar to the one the services have, which I have shown below:

```
  Clients_CoreData_Host: edgex-core-data
  Clients_Notifications_Host: edgex-support-notifications
  Clients_Metadata_Host: edgex-core-metadata
  Clients_Command_Host: edgex-core-command
  Clients_Scheduler_Host: edgex-support-scheduler
```

**Comment by bnevis-i** [comment]
I'm not completely satisfied with the above answers.  The gateway IS exposed on all ports and was not affected by the IP address lockdown.

```
edgex-ui-go:/go/src/github.com/edgexfoundry/edgex-ui-go/cmd/edgex-ui-server# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         192.168.192.1   0.0.0.0         UG    0      0        0 eth0
192.168.192.0   *               255.255.240.0   U     0      0        0 eth0
edgex-ui-go:/go/src/github.com/edgexfoundry/edgex-ui-go/cmd/edgex-ui-server# curl http://192.168.192.1:8000/
{"message":"no Route matched with those values"}
edgex-ui-go:/go/src/github.com/edgexfoundry/edgex-ui-go/cmd/edgex-ui-server# 
```

Here, I have proved connectivity to the gateway, from inside the container.
Yet if I choose 192.168.192.1 as the gateway address in the UI,
the UI still gives me a bad gateway message.

There must be more to it than this.  According to the above "connecting" to the gateway should work.

**Comment by DaveZLB** [comment]
> Yes, the lock down of the ports to `127.0.0.1` has broken the UI's ability to access the EdgeX services using a static IP or machine name since docker sees that as a network access. I attempted to use `127.0.0.1`, but that will not route outside the UI container.
> 
> This problem stems from the fact that the UI is trying to "connect" and "manage" a gateway rather than just "manage" the EdgeX instance that is is running within.
> 
> My suggestion is to drop the Gateway "connect" and use the docker network host names to connect to the services within the docker network. i.e. edgex-core-data:48080 & edgex-core-metadata:48081
> 
> This how all the service communicate with each other within the docker network. I suggest the UI have environment variables for the host names similar to the one the services have, which I have shown below:
> 
> ```
>   Clients_CoreData_Host: edgex-core-data
>   Clients_Notifications_Host: edgex-support-notifications
>   Clients_Metadata_Host: edgex-core-metadata
>   Clients_Command_Host: edgex-core-command
>   Clients_Scheduler_Host: edgex-support-scheduler
> ```
@lenny-intel , I agree with your solution, Although in  the same network(edgex-network) with other EdgeX services, UI  access the EdgeX services using a static IP, It is derived from historical design for managing multiple EdgeX instance.  UI still has a lot to improve, we will have a disscusion  later, thank you.

**Comment by badboy-huaqiao** [comment]
@mkbhanda @bnevis-i @lenny-intel @DaveZLB 
Hi all 😊

I saw this is repeated with issue-#222, I copied the reply message here to enhance the reminder.

Well, it looks a little weird.

I totally understand why you bind all services (except for kong) to native 172.0.0.1 with security on. under this way, user only can approach to edgexfoundry through the security API microservice kong.

However, without the security API microservice kong, how can users access edgexfoundry remotely?

In addition, it only makes sense when the UI can be remote access to , so the UI service should not also be bound to the native 127.0.0.1

The gateway term in the UI is essentially an edgexfoundry instance. We designed it with one view to managing multiple edgexfoundry instances with one UI, rather than one edgexfoundry instance with one UI, which is not conducive to the deployment of multiple edgexfoundry instances into a production environment.

But now the gateway term doesn't seem to be working as well as it should be, or not to make much sense at this point.

Therefore, we will remove the gateway concept in the next release.
However, in order to solve the current problem, I propose to modify the docker-compose file as follows：

the UI section in the docker-compose file:

<img width="510" alt="image" src="https://user-images.githubusercontent.com/16172215/82111559-a2b71a80-9778-11ea-9e12-27c451d1056b.png">

**Comment by badboy-huaqiao** [comment]
By the way, under this way , the user can only enter the value 172.0.0.1

**Comment by bnevis-i** [comment]
> However, without the security API microservice kong, how can users access edgexfoundry remotely?

If one is using the security-enabled docker-compose, one **must** go through Kong.  The underlying microservices implicitly trust every caller.  Kong is the only protection today.  On the other hand, if one doesn't care abut security, one can run the no-secty docker-compose scripts, which do expose ports, and the UI should work as it always has on this configuration.  (I don't recommend it, but it should work.)

> In addition, it only makes sense when the UI can be remote access to , so the UI service should not also be bound to the native 127.0.0.1
> (followed by workaround of binding edgex-ui-go to the host network stack and exposing the port)

While this will work in the short term, in the long term is not a correct solution either, in my opinion.  Long term, EVEN THE UI should be routed through the Kong proxy in the security-enabled configuration (perhaps with a custom authentication handler).  (It can even listen on a second port, if you wish, as long as it goes through Kong.  Otherwise, we will need to create a whole separate TLS infrastructure for the UI because it has a directly exposed port.)  Thus, in a security-enabled EdgeX instance, Kong--and only Kong--should have a host-exposed port.

**Comment by badboy-huaqiao** [comment]
@bnevis-i sorry, I didn't get your point, you mean that the UI service should behind kong  or UI should call other services' API through kong proxy? 

if UI behind kong , so how to get authentication when user  first visits the UI ? how kong proxy the UI pages?

**Comment by bnevis-i** [comment]
> @bnevis-i sorry, I didn't get your point, you mean that the UI service should be behind kong or UI should call other services' API through kong proxy?

Depends on the use case:

* With regard to the discussion of exposing the UI to external callers by binding the UI to the host's port 4000 in order to make it remotely accessible, I am saying that the UI should be behind Kong and not directly exposed on the host. (In the case that it is decided the the UI manages the local instance.)
* With regard to managing a remote instance, should that be the direction that is taken, I mean calling other services API through the Kong proxy.

> if UI behind kong , so how to get authentication when user first visits the UI ? how kong proxy the UI pages?

Most reverse proxies can route request and apply authentication on host name, ports, and URLs.   In the simplest case, Kong would simply pass the UI requests trough.  Alternatively, one could could using a Kong plugin, such as the HTTP Basic authentication plugin, to require a username and password in order to access the UI pages (and the UI could be locked down to require that it is being accessed via Kong)

**Comment by badboy-huaqiao** [comment]
@bnevis-i ok, I got it. we will remove gateway concept, but we have to test how to proxy UI pages through kong.

**Comment by lenny-intel** [comment]
@mkbhanda, we have a phased approach to this. This PR is a quick work around which allows the UI to connect to the local instance (gateway) using 127.0.0.1 and makes the UI optional.
https://github.com/edgexfoundry/developer-scripts/pull/290

The UI team will remove the concept of a `Gateway` and simply connect to local services at 127.0.0.1
I feel that the above PR resolves this immediate issue and it can now be closed. New issues should be created for the removal of the `Gateway`, etc. Do you agree?

**Comment by DaveZLB** [comment]
ok, if this PR [edgexfoundry/developer-scripts#290](https://github.com/edgexfoundry/developer-scripts/pull/290) has been done, UI will work well when users input 127.0.0.1 in gateway page in current situation. Next , I will remove gateway page from ui in a new issue and connect EdgeX services using configuration way.

**Comment by DaveZLB** [comment]
Add another point , I need modify Registry Host value to localhost

**Comment by lenny-intel** [comment]
Ok, looks like this issue can be closed by someone who has privs, which I don't... ;-)
