### ISSUE TITLE
Upgrade Angular version to v 12.x to get clean npm audit scan

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-ui-go#369]
```console

$ cd web
$ npm audit
found 501 vulnerabilities (3 low, 89 moderate, 408 high, 1 critical) in 1504 scanned packages
  run `npm audit fix` to fix 432 of them.
  67 vulnerabilities require semver-major dependency updates.
  2 vulnerabilities require manual review. See the full report for details.
```

**Comment by badboy-huaqiao** [comment]
@bnevis-i great thanks for your feedback, we will check out that

**Comment by bnevis-i** [comment]
@badboy-huaqiao is this going to be updated for Ireland release?

**Comment by badboy-huaqiao** [comment]
@bnevis-i we're still doing research, and we need to consider whether upgrading dependent libraries to the latest version will have an unintended impact on the work we've done so far

**Comment by badboy-huaqiao** [comment]
@bnevis-i we have updated some dependent libraries, but some of them needed to be forced fixed which will caused the projected failed to start, and  most of this  high vulnerability libraries  is just used in develop environment, so I think they should be ignored.

so what do you think?

<img width="746" alt="image" src="https://user-images.githubusercontent.com/16172215/123034316-d94f7200-d41b-11eb-9d70-060b9b6a0d17.png">

**Comment by badboy-huaqiao** [comment]
@bnevis-i  I have updated most of the dependent libraries which is vulnerabilities, as i mentioned above before, there are 2 high dependencies should not be fixed manually which will cause to failed to build the project with `ng build `command, and they are just used in develop environment instead of production environment, and there are 5 moderate,3 low dependent libraries needs the ui update the whole angular framework to v12.x,  we should do that next time. so I think we can ignore them.
the following is the report of `npm audit` command after updates:
```
found 10 vulnerabilities (3 low, 5 moderate, 2 high) in 1495 scanned packages
  run `npm audit fix` to fix 2 of them.
  7 vulnerabilities require semver-major dependency updates.
  1 vulnerability requires manual review. See the full report for details.
```
