### ISSUE TITLE
RuleEngine rule MQTT action default value of  ProtocolVersion doesn't work

### ISSUE THREAD

**Issue by ngjaying** [edgexfoundry/edgex-ui-go#413]
Steps to reproduce:

- Create a stream
- Create a rule: In rule list, click Add
- Enter any rule id and SQL, click Next
- Select "Send the result to an MQTT broker.", in the right form, fill in "Server" and "Topic"
- Click "Submit".

Result:
 The rule is created but the status is "Stopped: canceled manually or by error."

Expect:
The rule can run successfully. 

Root cause:
The default value for ProtocolVersion is 3.1. which is invalid, shoudl be 3.1 or just empty.

**Comment by badboy-huaqiao** [comment]
others:
1. 
 -  It is likely that the UI post a wrong data type for sendSingle property.

   The sendSingle must be a bool instead of a string type.

   ![img](https://user-images.githubusercontent.com/16983/140176239-ac93abd0-f40a-4532-a8b4-f6c63d047a2b.png)

   

  - The Http Method part can not automaticly load "GET" "PUT" method etc

  - RetryInterval can be removed

   

2. Sink for Mqtt Broker error

   Root cause:
   The default value for ProtocolVersion is 3.1. which is invalid, shoudl be 3.1 or just empty.

   can design as drop down list , value is 3.1 or 3.1.1

3. Sink for edgeX error

   - Optional field can be designed to multi-row. if user do not fill it, do not send "optional" to backend 

   - port should be int type
   - add the edgex v2 new added parameters
     * message type 
     * topicPrefix

**Comment by badboy-huaqiao** [comment]
see PR-#502, it's done!
